FROM python:3.9-slim-bullseye

WORKDIR /home
COPY requirements.txt .
RUN pip install -r requirements.txt

RUN apt update
RUN apt install git -y

RUN git clone https://github.com/ndominutti/SysDesign_OnlineRecommendationEngine.git

RUN cp -r SysDesign_OnlineRecommendationEngine/api/app /home/app

CMD ["uvicorn", "app.main:app", "--reload", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000"]
